// react/src/App.tsx
import { Textigniter } from '@mindfiredigital/textigniter-react';

function App() {
  return (
    <Textigniter
      config={{
        showToolbar: true,
        features: [
          'bold',
          'italic',
          'underline',
          'fontFamily',
          'fontSize',
          'fontColor',
          'alignLeft',
          'alignCenter',
          'alignRight',
          'unorderedList',
          'orderedList',
          'hyperlink',
          'image',
        ],
      }}
    />
  );
}

export default App;

// angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { TextIgniterModule } from '@mindfiredigital/textigniter-angular';

@Component({
  selector: 'app-root',
  imports: [TextIgniterModule],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent {
  title = 'TextIgniter Angular Demo';

  config = {
    showToolbar: true,
    features: [
      'bold',
      'italic',
      'underline',
      'hyperlink',
      'fontFamily',
      'fontSize',
      'alignLeft',
      'alignCenter',
      'alignRight',
      'unorderedList',
      'orderedList',
      'image',
      'fontColor',
      'bgColor',
      'getHtmlContent',
      'loadHtmlContent'
    ]
  };

  editorContent = { html: '', text: '' };

  onContentChange(content: { html: string; text: string }) {
    this.editorContent = content;
    console.log('Editor content changed:', content);
  }
}

<div class="container">
  <h1>{{ title }}</h1>
  <p class="subtitle">A rich text editor component for Angular</p>

  <div class="editor-section">
    <h2>Editor</h2>
    <ngx-text-igniter
      [config]="config"
      editorId="main-editor"
      (contentChange)="onContentChange($event)"
    ></ngx-text-igniter>
  </div>

  <div class="output-section">
    <h2>Output Preview</h2>

    <div class="output-box">
      <h3>HTML Output</h3>
      <pre>{{ editorContent.html }}</pre>
    </div>

    <div class="output-box">
      <h3>Plain Text Output</h3>
      <pre>{{ editorContent.text }}</pre>
    </div>
  </div>
</div>
